version: "3.5"

services:
  jekyll-text-theme_build:
    image: docker_jekyll-text-theme_dev
    environment:
      - JEKYLL_ENV
    ports:
      - "127.0.0.1:4000:4000"
    container_name: jekyll-text-theme_build
    volumes:
      - ..:/usr/src/app
    command: bundle exec jekyll build

  jekyll-text-theme_web:
    image: nginx
    ports:
      - 80:80
      - 443:443
    container_name: static_web_prod
    restart: unless-stopped
    volumes:
      - ../_site:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/blog.cartensz-explorer.com:/etc/letsencrypt/live/blog.cartensz-explorer.com
    depends_on:
      - jekyll-text-theme_build
